### PR TITLE
fix duplicate Running labels

### LINKED ISSUE #48: bug: fix the retry button displaying the `running` state on all the buttons instead of just the one individual test.
To reproduce: 
- Run one or more test suites that will have more than one test failing. 
- A retry button should show up directly below each test. 
- Hitting the `Retry` button will then restart the specific test and change its text to `Running` but the text in **all** the buttons will also switch to `Running` which is incorrect. 
image

### PR DESCRIPTION
**Pull request by cvaldez98**
I fixed the problem where clicking the 'Run test' button would change the state of _all_ the buttons rather than just that specific one. This fixes #48 but I am not sure if this is the best way to fix this. @felixrieseberg what do you think? Good enough?

### CODE REVIEW

File: src/renderer/state.ts [hunk 1]
```diff
@@ -51,6 +51,7 @@ export class AppState {
   // Used for button retry info
   @observable public testRunning: boolean = false;
```
Comment (felixrieseberg) [inline src/renderer/state.ts]: Could we alternatively just turn `testRunning` into a `string | undefined`?

Comment (cvaldez98) [reply src/renderer/state.ts]: Yeah! That's much better actually. ✅
